language: java
jdk:
 - oraclejdk8
 #- openjdk8

after_success:
# - mvn clean verify -Ptravis jacoco:report coveralls:report
 - mvn clean verify -Ptravis jacoco:report codacy:coverage
 - mvn clean verify -Ptravis jacoco:report sonar:sonar