language: java
jdk:
 - openjdk8
 - oraclejdk8

after_success:
# - mvn clean verify -Ptravis jacoco:report coveralls:report
 - mvn clean verify -Ptravis jacoco:report codacy:coverage
 - mvn clean verify -Ptravis jacoco:report sonar:sonar